


##@server = https://teoo01p-expert-space-spork-9rr99766gv6fpx6g-8080.preview.app.github.dev

@server=https://ec03teodora.onrender.com
@api={{server}}/api/ec3
###

GET {{server}}/

###
GET {{api}}/categorias

###


GET {{server}}/categorias

##
POST {{api}}/categorias
Content-Type: application/json

{"nombre": "Articulos de limpieza"}


###
PATCH {{api}}/categorias/2
Content-Type: application/json

{"nombre": "Articulos de cocina"}



###

GET {{api}}/instrumentos


###
GET {{api}}/instrumentos?size=2&page=3


##########

GET {{api}}/instrumentos

###

POST {{api}}/instrumentos
Content-Type: application/json

{"nombre": "Jabon"}

##########

GET {{api}}/categorias/1/instrumentos