


##@server = https://teoo01p-expert-space-spork-9rr99766gv6fpx6g-8080.preview.app.github.dev

@server=https://ec03teodora.onrender.com

###

GET {{server}}/

###
GET {{server}}/categorias

###
POST {{server}}/categorias
Content-Type: application/json

{"nombre": "Articulos de limpieza"}


###
PATCH {{server}}/categorias/2
Content-Type: application/json

{"nombre": "Articulos de cocina"}



###

GET {{server}}/instrumentos


###
GET {{server}}/instrumentos?size=2&page=3


##########

GET {{server}}/instrumentos

###

POST {{server}}/instrumentos
Content-Type: application/json

{"nombre": "Jabon"}

##########

GET {{server}}/categorias/1/instrumentos

##########

GET {{server}}/cursos/6/carrera